token:
  expiration_time: 864000000 #1day token
  secret: a-very-long-secret-key-that-is-at-least-64-bytes-laaa

gateway:
  ip: 192.168.0.6
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}7ed02ca6b84295b79240466d056215aacadf004ec3f02a2822c3807e47b4894f'
